Feature move 2420 avoid restart forcing update
felleslosninger/efm-deploy-manager pull request #54
Opened 2021-05-05 16:03 UTC by jaflaten

Gjenstår å fikse testar og cucumber testar, men første utkast til funksjonalitet implementert.

2021-05-06 14:20 UTC, martinwam requested changes
Mest småplukk, men tror DeployDirectoryRepo.getAllowlistFile() bør sees på da den i tilfeller hvor det mot formodning skulle eksistere flere allow-filer kan returnere feil "siste"-versjon. Fra javadoc til File: "There is no guarantee that the name strings in the resulting array will appear in any specific order; they are not, in particular, guaranteed to appear in alphabetical order."

2021-05-06 14:20 UTC, martinwam commented on src/main/java/no/difi/move/deploymanager/action/application/StartAction.java
> +            deployDirectoryRepo.allowlist(jarFile, String.format("integrasjonspunkt-%s.allowlisted", application.getLatest().getVersion()));
Kanskje flytte "integrasjonspunkt-%s.allowlisted" som en static til deployDirectoryRepo, da den er brukt flere steder, og kun ta version som parameter?

2021-05-06 14:20 UTC, martinwam commented on src/main/java/no/difi/move/deploymanager/repo/DeployDirectoryRepo.java
> +            log.debug("Allowlist {} created: {}", file.getName(), created);
Her er det vel "allowlistFile" som har blitt opprettet?

2021-05-07 06:58 UTC, jaflaten commented on src/main/java/no/difi/move/deploymanager/action/application/StartAction.java
> +                deployDirectoryRepo.removeAllowlist(deployDirectoryRepo.getFile(version, "integrasjonspunkt-%s.allowlisted"));
På ein måte ja, men då må den ned og leite på disk etter filer igjen og utføre den i staden for å berre få det som parameter, meinar at det vert raskare slik sidan ein unngår io-kallet.

2021-05-07 07:00 UTC, jaflaten commented on src/main/java/no/difi/move/deploymanager/repo/DeployDirectoryRepo.java
> +    public File getAllowlistFile() {
Har i utgangspunktet forventa at det kun vil være ei .allowlisted fil tilgjengelig fordi om ein oppdaterar til ny versjon vil den rydde opp den gamle og heller opprette ei ny for gjeldande versjon. Dermed skulle den kunne finne det den treng på array[0] basert på det som kjem frå mappa, men kan nok være lurt å legge inn ein sjekk her..

tenker at om eg sjekkar og ser kor mange filer eg fekk, visst 1 så gjer som før, visst fleire så sjekka eg kass av dei som har høgaste versjonsnummer og velge denne.

2021-05-07 07:15 UTC, jaflaten commented on src/main/java/no/difi/move/deploymanager/action/application/StartAction.java
> +            deployDirectoryRepo.allowlist(jarFile, String.format("integrasjonspunkt-%s.allowlisted", application.getLatest().getVersion()));
Skal fikse.

2021-05-07 07:36 UTC, martinwam commented on src/main/java/no/difi/move/deploymanager/action/application/StartAction.java
> +                deployDirectoryRepo.removeAllowlist(deployDirectoryRepo.getFile(version, "integrasjonspunkt-%s.allowlisted"));
Men det gjøres to linjer over uansett med deployDirectoryRepo.getAllowlistVersion(). Kunne ev. hentet fila der i stedet, og utledet versjon fra den, så ta fil som parameter for sletting, så slipper du unna med én leteoperasjon.

2021-05-07 07:49 UTC, martinwam commented on src/main/java/no/difi/move/deploymanager/repo/DeployDirectoryRepo.java
> +    public File getAllowlistFile() {
Jepp, med på den. Bare tenker at det kan være greit å planlegge for det uforutsette her, siden det er snakk om eksterne filer. Plutselig har f.eks en annen prosess hijacket fila så sletting feiler, og da ender man opp med flere. En annen mulighet er kanskje å heller alltid ha én allowlist-fil (json/yaml) som inneholder allow-versjoner? Da slipper man å traversere/lete gjennom disk for å finne matchende filer.

2021-05-07 07:52 UTC, jaflaten commented on src/main/java/no/difi/move/deploymanager/action/application/StartAction.java
> +                deployDirectoryRepo.removeAllowlist(deployDirectoryRepo.getFile(version, "integrasjonspunkt-%s.allowlisted"));
Skriv om removeAllowlist(...) til å ta kun versjon i staden, så kan eg utlede resten i DeployDirectoryRepo.

2021-05-14 05:31 UTC, FrodeBjerkholt approved these changes

2021-05-18 09:13 UTC, merged